### ISSUE TITLE
Nav Update: Improve CSS rules for `.nav-links` in `nav.scss`

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#2360]
Follow-up ticket for https://github.com/mozilla/foundation.mozilla.org/pull/1770#discussion_r242353191 and https://github.com/mozilla/foundation.mozilla.org/pull/1770#discussion_r242353865

Improve CSS rules for `.nav-links` in `nav.scss` so we can stop using `!important`

```scss
@at-root {
  #view-people .nav-link-people,
  #view-initiatives .nav-link-initiatives,
  #view-projects .nav-link-projects,
  #view-participate .nav-link-participate,
  #view-internet-health .nav-link-internet-health,
  #view-about .nav-link-about {
    border-color: black !important;

    @include hover-focus-active {
      border-color: initial !important;
    }
  }
}
```
