### ISSUE TITLE
improve the CSS for the PNI post-vost share dialog

### ISSUE THREAD

**Issue by Pomax** [mozilla/foundation.mozilla.org#2618]
Based on https://github.com/mozilla/foundation.mozilla.org/pull/2584#discussion_r254499647:

---

<@mmmavis> It'd better if we let elements adjust width themselves instead of setting multiple sets of fixed width and margin. I would simplify the following SCSS to

```scss
.pni-share-buttons {
  max-width: 568px; // width from comps
  margin: 0 auto;

  .pni-s-link {
    $margin-x: 0.5rem;

    border: 1px solid black;
    border-bottom-width: $btn-shadow-width;
    color: black;
    transition: all 0.1s linear;
    border-radius: 2em;
    white-space: nowrap;
    margin-bottom: 1rem;
    padding: 0.5em 0;
    font-weight: 600; // this should be semi-bold so 600
    flex: 1;

    @media screen and (max-width: $bp-md) { // Generally we want to avoid using "max-width" since we write our SCSS in mobile first style. This is an exception here since we want these rulesets to apply only on mobile and using "max-width" is the cleanest solution here.
      &:nth-child(odd) {
        margin-right: $margin-x;
      }

      &:nth-child(even) {
        margin-left: $margin-x;
      }
    }

    @media screen and (min-width: $bp-md) {
      margin-left: $margin-x;
      margin-right: $margin-x;

      &:first-child {
        margin-left: 0;
      }

      &:last-child {
        margin-right: 0;
      }
    }

    @include hover-focus-active {
      ...
```
(don't forget to remove my inline comments)
