### ISSUE TITLE
SCSS cleanup: assign breakpoint variables to a common variable 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/foundation.mozilla.org#4471]
Similar to what we did in https://github.com/mozilla/foundation.mozilla.org/pull/4467/files#diff-a7e457c11566b243d750e6a6acd87ad7

```scss
.parent-class {
  @media screen and (min-width: $bp-lg) {
    // blah blah
  }

  .child-class {
    // blah blah

    @media screen and (min-width: $bp-lg) {
      // blah blah
    }
  }

  .child-class-2 {
    // blah blah

    @media screen and (min-width: $bp-lg) {
      // blah blah
    }
  }

  ...
  ...
  ...
}
```

Can be simplified to

```scss
.parent-class {
  $breakpoint: $bp-lg;

  @media screen and (min-width: $breakpoint) {
    // blah blah
  }

  .child-class {
    // blah blah

    @media screen and (min-width: $breakpoint) {
      // blah blah
    }
  }

  .child-class-2 {
    // blah blah

    @media screen and (min-width: $breakpoint) {
      // blah blah
    }
  }

  ...
  ...
  ...
}
```

This way if we ever need to update breakpoint to something else (for example, `$bp-lg` to `$bg-md`) we only have to update the `$breakpoint` variable assignment instead of find-and-replace multiple times in the same parent class ruleset scope.
